#ifndef GLOBAL_DEFINES_H
#define GLOBAL_DEFINES_H

#define I2S_CLOCK               20000000
#define SAMPLING_FREQUENCY      (I2S_CLOCK/512)
#define DOWNSAMPLE_FACTOR       (SENSED_SIZE/SAMPLES_SIZE)
#define DOWNSAMPLED_FREQUENCY   (SAMPLING_FREQUENCY/DOWNSAMPLE_FACTOR)

#define SAMPLES_SIZE            256
#define SENSED_SIZE             SAMPLING_FREQUENCY/10

#define SENSING_RATE            1000000



#define DOWNSAMPLED__FFT        16
#endif
